name: another start
on: [push]
jobs: 
    runs-on-push:
          runs-on: ubuntu-latest
          steps:
             - run: echo "run successfully"
    runs-on-push2:
          runs-on: ubuntu-latest
          steps:
             - run: echo "run successfully again"
       