name: github Actions
on: [push]
jobs: 
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with: 
                  node-version: 14
            - name: running the tree      
                  run: tree
            - name: checking the node version
                  run: node -v
            - name: build the project
                  run: npm build
